const setups = require("../schemas/setup")
const moment = require("moment");
require("moment-duration-format");
moment.locale("tr");
const a = require("../configs/settings.json")
let iltifatSayi = 0;
let iltifatlar = [
"Yaşanılacak en güzel mevsim sensin.",
"Sıradanlaşmış her şeyi, ne çok güzelleştiriyorsun.",
"Gönlüm bir şehir ise o şehrin tüm sokakları sana çıkar.",
"Birilerinin benim için ettiğinin en büyük kanıtı seninle karşılaşmam.",
"Denize kıyısı olan şehrin huzuru birikmiş yüzüne.",
"Ben çoktan şairdim ama senin gibi şiiri ilk defa dinliyorum.",
"Gece yatağa yattığımda aklımda kalan tek gerçek şey sen oluyorsun.",
"Ne tatlısın sen öyle. Akşam gel de iki bira içelim.",
"Bir gamzen var sanki cennette bir çukur.",
"Gecemi aydınlatan yıldızımsın.",
"Ponçik burnundan ısırırım seni",
"Bu dünyanın 8. harikası olma ihtimalin?",
"fıstık naber?",
"Dilek tutman için yıldızların kayması mı gerekiyor illa ki? Gönlüm gönlüne kaydı yetmez mi?",
"Süt içiyorum yarım yağlı, mutluluğum sana bağlı.",
"Müsaitsen aklım bu gece sende kalacak.",
"Gemim olsa ne yazar liman sen olmadıktan sonra...",
"Gözlerimi senden alamıyorum çünkü benim tüm dünyam sensin.",
"Sabahları görmek istediğim ilk şey sensin.",
"Mutluluk ne diye sorsalar, cevabı gülüşünde ve o sıcak bakışında arardım.",
"Hayatım ne kadar saçma olursa olsun, tüm hayallerimi destekleyecek bir kişi var. O da sensin, mükemmel insan.",
"Bir adada mahsur kalmak isteyeceğim kişiler listemde en üst sırada sen varsın.",
"Sesini duymaktan- hikayelerini dinlemekten asla bıkmayacağım. Konuşmaktan en çok zevk aldığım kişi sensin.",
"Üzerinde pijama olsa bile, nasıl oluyor da her zaman bu kadar güzel görünüyorsun? Merhaba, neden bu kadar güzel olduğunu bilmek istiyorum.",
"Çok yorulmuş olmalısın. Bütün gün aklımda dolaşıp durdun.",
"Çocukluk yapsan da gönlüme senin için salıncak mı kursam?",
"Sen birazcık huzur aradığımda gitmekten en çok hoşlandığım yersin.",
"Hangi çiçek anlatır güzelliğini? Hangi mevsime sığar senin adın. Hiçbir şey yeterli değil senin güzelliğine erişmeye. Sen eşsizsin...",
"Rotanızı geçen her geminin ışığıyla değil, yıldızlara göre ayarlayın.",
"Telaşımı hoş gör, ıslandığım ilk yağmursun.",
"Gülüşün ne güzel öyle, cumhuriyetin bir gelişi gibi sanki",
"Ne yaparsan yap, sen her zaman çok doğalsın.",
"Sen, tanıdığım en cesur insansın. Keşke senin gibi olabilseydim.",
"Sen tanıdığım en tatlı insansın.",
"Seninle konuşmak, ferah bir nefes almak gibidir.",
"Bugün harika iş çıkardın. Seninle çalışmayı çok seviyorum.",
"Enerjinin bulaşıcı olduğunu kendi gözlerimle gördüm. Sen mükemmel bir insansın.",
"O kadar nazik ve anlayışlısın ki etrafındaki herkesi daha iyi bir insan yapmayı başarıyorsun.",
"En kötü durumları bile eğlenceli bir hale dönüştürmene bayılıyorum.",
"Keşke senin kadar mükemmel bir insan olabilseydim.",
"Yaratıcılığın çok yüksek bir seviyede.",
"İnsanlara güvenmeni seviyorum. Bu anlayışının bir kısmını bana gönderir misin?",
"Ünlü olduğun zaman, hayran kulübünün tek başkanı olmak istiyorum.",
"Çocuklarına çok iyi örnek oluyorsun. Her şeyi doğru yapmana bayılıyorum.",
"Sen yeri doldurulamaz bir insansın.",
"Farkında olduğundan daha harikasın.",
"Senin gibi bir arkadaşımın olması özel hissetmeme neden oluyor.",
"Beni hiçbir zaman hayal kırıklığına uğratmıyorsun. Ne olursa olsun sana güvenebileceğimi biliyorum.",
"Senin yanında olduğum zaman kendimi çok şanslı ve özel hissediyorum.",
"Makyaj doğal güzelliğini kapatıyor resmen.",
"Saçların denizin huzurunu yansıtıyor.",
"Senin gülümsemen benim en derin mutluluğum.",
"Harika bir tarzın var. Tarzına sahip olmayı çok isterdim.",
"Sen herkesin hayatında olması gereken bir insansın.",
"Masallardaki prensesin şekil bulmuş halisin.",
"Şarkılarımın, şiirlerimin ilham kaynağısın.",
"Yanında hissetmediğim güven ve huzuru hissediyorum.",
"Bu kadar tatlı olmayı nasıl başarıyorsun?",
"Gözlerin en güzel ışık kaynağım.",
"En güzel iyikimsin.",
"Yaşadığım tüm kötülüklere sen karşıma alıp izleyerek baş edebilirim.",
"Çiçekleri kıskandıran bir güzelliğe sahipsin.",
"Sen benim tüm imkansızlıklarıma rağmen hayattaki en değerlimsin",
"Sen benim en güzel manzaramsın.",
"Enerjin içimi aydınlatıyor",    
"Oha bu çocuk Türk müüüüüüüüüüüü?",
"dur beynimi çıkarayım, eşit şartlarda konuşalım",
"gitsen tek kaybım mal kaybı olur hahaha",
"bunun adı kalp güzelim. Tersten okuduğun gibi plak değil ki sürekli sende takılı kalsın.",
"kafamı yaşasan kafana sıkarsın",
"sanırım seni getiren leyleğin bıraktığı izdi, kuş beyinli olman.",
"senin için savaşırdım ama verimsiz toprakları feth etmeye gerek yok",
"birbirimizi çift görmem için kaç duble daha içmeliyim?",
"azrail bile ayağıma geliyor ne bu tripler?",
"Buralarda yeniyim de kalbinin yolunu tarif eder misin?",
"Nasıl yani şimdi sen gerçek misin?",
"Bunca zaman neredeydin ?",
"seni seviyorum.",
"Allah seni yaratmış fakat takip etmiyor sanırım, bu tip ne?",
"sarılalım mı?",
"benimle evlenir misin?",
"azıcık beynini kullan diyeceğim fakat seni zor durumda bırakmak istemiyorum.",
"akıllara zarar bi mükemmelliğin var",
"attan indiysek leopar falan gelmiştir ben anlamam eşekten",
"dedikodu yapalım mı?",
"iyi ki varsın 💕",
"şu üstteki aptik ne anlatıyor ya?",
"o kadar haklısın ki... seni öpesim var",
"öpşuelimi? çabuk!",
"yavrum hepsi senin mi?",
"bi alo de gelmezsem gençliğim solsun.",
"çok şişkosun.",
"sevgilim var yazma?",
"zenginsen evlenelim mi?",
"halk pazarı gibisin canım sana olan tek ilgim ucuzluğundan",
"o kadar çok meslek türü varken neden şerefsizlik tatlım?",
"bu güne aynayı öperek başladım",
"çok bereketli topraklarımız yok mu? her türlü şerefsiz yetişiyor",
"taş gibisin!",
"kalitesizliğinin kokusu geldi...",
"Şey gözlerin çok güzelmiş tanışalım mı ?",
"Kalbinin yolunu gösterir misin...",
"Corona olsan bile sana sarılırdım",
"Oha sen gerçek misin ?",
"kahveyi sütsüz seni tereddütsüz seviyorum",
"senin hava attığın yerde benim rüzgarım esiyor",
"çok güzel bi tablo gördüm tam alacaktım ama aynaymış...",
"canım haddin hariç her şeyi biliyorsun",
"havalar alev gibii, tatile serin bi yerlere gitsene mesela morg?",
"tavla oynayalım ama sen beni tavla",
"hava sıcak değil aşkından yanıyorum",
"konum atta belamızı bulalım bebeğim",
"üşüdüysen sana abayı yakayım mı?",
"gel biraz otur yanıma ölünce gidersin",
"sütüm yarım yağlı mutluluğum sana bağlı",
"eğer ahtapot olsaydım üç kalbimi de sana verirdim",
"salağa yatarken uyuya falan mı kaldın?",
"meleksin ama canımı alıyorsun yoksa Azrailim misin?",
"ben varya fay hattı olsam kesin daha az kırılırdım",
"iban at hayallerimi yollayayım harcarsın",
"ankarada deniz sende karakter",
"sana hayatım diyorum çünkü o kadar kötüsün",
"görüşelim mi? mahşer yeri uygun mu?",
"eşekten yarış atı olmaz ama sen genede koş spor yaparsın",
"Anlatsana biraz neden bu kadar mükemmelsin?",
"Nasılsın diye sorma bebeğim, sana göreyim kıpss",
"Kakaolu sütsün seni sevmeyen ölsün",
"Ya sen hep böyle hoşuma mı gideceksin ?",
"Çikolatalı keksin bu alemde teksin",
"8 milyar gülüş varken seninki favorim",
"dalin gibi kokuyorsun",
"seni her gün görenlerin şansından istiyorum",
"en iyisine layıksın yani bana hıh",
"ateşimin çıkma sebebi corona değil, sensin",
"yemeğimi yedim şimdi seni yeme vakti",
"beni biraz takar mısın?",
"aklın başına gelir ama ben sana gelmem",
"sen beni birde sevgilinken gör",
"naber lan karakter kanseri",
"soğuk davranacaksan üzerime bir şey alayım?",
"sana beyin alacam",
"Allah belanı vermiyor artık ben bir şey yapacağım",
"artık benimsin",
"o kadar pubg oynadım böyle vurulmadım",
"canın yandı mı? cenneten düşerken?",
"seni mumla ararken elektrikler geldi",
"burnunda sümük var",
"Suyun içinde klorür senin kalbinde bir ömür...",
"Çok tatlı olmayı bırak artık... Kalbim başa çıkamıyor !",
"Kalbini dinle dediklerinde seni dinleyesim geliyor",
"Polisi arıyorum çünkü bu kadar tatlı olman yasadışı !",
"Ölüm ani dünya fani bi kere sevsen nolur ki yani ?",
"Bana yüzünü dönme gece oluyor sanıyorum.",
"Güneş aya ben sana tutuldum.",
"Sana gemi alalım dümende bir numarasın.",
"AÇILIN DÜNYANIN 8.HARİKASI GELDİ !",
"Ben küçücük bi botum ama sana kocaman sarılırım",
"Kafam çok güzel çünkü içinde sen varsın.",
"Alnın güzelmiş yazısı olabilir miyim ?",
"Gülüşün şimşek içermiyiz birer milkşeyk ?",
"Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
"Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
"Mavi gözlerin, gökyüzü oldu dünyamın.",
"Seni gören kelebekler, narinliğin karşısında mest olur.",
"Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
"Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
"Huzur kokuyor geçtiğin her yer.",
"En güzel manzaramsın benim, seyretmeye doyamadığım.",
"Sen benim düşlerimin surete bürünmüş halisin.",
"Bir sahil kasabasının huzuru birikmiş yüzüne.",
"Gülüşünde nice ilaçlar var yarama merhem olan.",
"Gece nasıl sabahı bekliyorsa aydınlanmak için ben de seni öyle bekliyorum.",
"Işığınla gecemi aydınlatıyorsun.",
"Yağmurdan sonra açan gök kuşağı gibisin, öyle güzel ve özel!",
"Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
"Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
"Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
"Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
"Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
"Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
"Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
"Senin güzelliğini anlatmaya dünyalar değil, lisanslar bile yetmez.",
"Etkili gülüş kavramını ben senden öğrendim.",
"Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
"Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
"Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan her toprak benim de vatanımdır.",
"Gözlerinle baharı getirdin garip gönlüme.",
"Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
"Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
"Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
"Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
"Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
"Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
"Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
"Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
"Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
"Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
"Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
"Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
"Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
"Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
"Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
"Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
"Aklıma sevmek geldiğinde, gözlerimin önüne sen geliyorsun. Günün her saati canım sevmek istiyor ve seni düşünüyor kalbim",
"Tak jileti dudağına öp beni şah damarımdan!"]   
module.exports = async (message) => {
if(!message.guild) return;
const ayar = await setups.findOne({guildID: a.guildID})
if(!ayar) return; 
if (message.channel.id === ayar.chatChannel && !message.author.bot) {
iltifatSayi++;
if (iltifatSayi >= 100) {
iltifatSayi = 0;
message.reply({ content: `**${iltifatlar.random()}**`}).catch(e => {});
};
};
}; 
module.exports.conf = {
name: "messageCreate",
};
